spring:
  batch:
    job:
      names: ${job.name:NONE}
#  main:
#    allow-bean-definition-overriding: true
#  jpa:
#    properties:
#      hibernate:
#        format_sql: true
#    database: mysql
#    generate-ddl: false
#    show-sql: true

#logging:
#  level:
#    org.springframework.web : debug
#    sql: debug
#    jdbc: debug
#    jdbc.sqlonly: debug
